### ISSUE TITLE
Avoid error shows up when filter has nothing.

### ISSUE THREAD

**Issue by hsiaoyi0504** [NCBI-Hackathons/SCRVV#14]

**Comment by lindsayrutter** [comment]
Hi Leo, do you mean the error that shows when a selectizeInput() field has zero values selected? If so, I used a validate(need()) structure that provides a more detailed error message to the user if they have a selectizeInput() field with zero values selected.

**Comment by hsiaoyi0504** [comment]
Yes, I mean the issue you mentioned earlier during the hackathon.

**Comment by lindsayrutter** [comment]
Okay, great. I think it is fixed now. If you think otherwise, feel free to let me know.
