### ISSUE TITLE
Remove meaningless indices in the unique tab of application

### ISSUE THREAD

**Issue by lindsayrutter** [NCBI-Hackathons/SCRVV#20]
Remove meaningless indices in the unique tab of Shiny application, and allow more than six factor levels to be listed in the summary tab of Shiny application

**Comment by hsiaoyi0504** [comment]
I think it will be good to move the information in unique into summary tab.

**Comment by lindsayrutter** [comment]
Hi Leo, I updated the Shiny app. There is now only one "Column Summary" tab. I tried to simplify and clean up the output. If you agree in its new format, we can close this Issue.

**Comment by hsiaoyi0504** [comment]
LGTM. closed.
