### ISSUE TITLE
Dependencies for Visuals.R

### ISSUE THREAD

**Issue by lindsayrutter** [NCBI-Hackathons/SCRVV#7]
library(shiny)
library(tidyr)
library(ggplot2)
library(plotly)
library(dplyr)

**Comment by dytk2134** [comment]
library(DT)

**Comment by hsiaoyi0504** [comment]
library(ggplotly)

**Comment by hsiaoyi0504** [comment]
All fixed until https://github.com/NCBI-Hackathons/ViRGo/commit/e50cc21473264976b8ef0814572ee712b16a30df.
